nelmio_cors:
    defaults:
        allow_credentials: false
        max_age: 0
        forced_allow_origin_value: ~
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'appKey']
