version: '2.2'

# Let's build all the services required to run this app (dev version)
# We need -
# MySQL => Database
# Nginx => Web Server
# PHP-FPM
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: zenoshidb  # Database will be created on start
      MYSQL_USER: zenoshi      # Password for MySQL User.
      MYSQL_PASSWORD: w4nmTQQvKeC2N3we
    # We need to run healthcheck because we need to make sure that the initial & default
    # database has been created
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=symfony --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  symfony:
    container_name: symfony
    build:
      context: .
      dockerfile: ./infrastructure/containers/symfony/Dockerfile
    command: ./prepare.sh   # Reset database, run migration + fixtures
    volumes:
      - ./var:/var/www/html/var
    environment:
      DATABASE_URL: mysql://zenoshi:w4nmTQQvKeC2N3we@teamq_db:3306/zenoshidb?serverVersion=5.7
      APP_ENV: dev  # For debugging purpose we built it as a dev version
    links:
      - mysql
    # Database must be ready before running this searvice
    depends_on:
      mysql:
        condition: service_healthy    # DB service must be in healthy state to start this App
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./infrastructure/containers/nginx/Dockerfile
    ports:
      - "8011:80"   # Webserver will run on http://localhost:8011
    depends_on:
      - symfony     # Web App service must be running
      - mysql          # DB must be ready