version: '3.4'
services:
  apache:
    image: apache:local
    build:
      context: ./
      dockerfile: ./infrastructure/containers/apache/Dockerfile
      target: production
    container_name: apache
    networks:
     - app
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
  php:
    image: php:local
    build:
      context: ./
      dockerfile: ./infrastructure/containers/php/Dockerfile
      target: production
    environment:
      - APP_ENV=production
    networks:
      - app
networks:
  app:
    driver: bridge
