version: '2.2'

# Let's build all the services required to run this app (dev version)
# We need -
# MySQL => Database
# Nginx => Web Server
# PHP-FPM
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ZHjA3t2wgqu642kL
      MYSQL_DATABASE: zenoshidb  # Database will be created on start
      MYSQL_USER: zenoshi      # Password for MySQL User.
      MYSQL_PASSWORD: w4nmTQQvKeC2N3we
  symfony:
    image: symfony_zenoshi:lastest
    container_name: symfony
    build:
      context: .
      dockerfile: ./infrastructure/containers/symfony/Dockerfile
    volumes:
      - ./var:/var/www/app/var
    environment:
      DATABASE_URL: mysql://zenoshi:w4nmTQQvKeC2N3we@teamq_db:3306/zenoshidb?serverVersion=5.7
      APP_ENV: prod
    links:
      - mysql
    # Database must be ready before running this searvice
    depends_on:
      mysql:
        condition: service_healthy    # DB service must be in healthy state to start this App
  nginx:
    image: nginx_zenoshi:lastest
    container_name: nginx
    build:
      context: .
      dockerfile: ./infrastructure/containers/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - symfony     # Web App service must be running
      - mysql          # DB must be ready