parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    # env(DATABASE_URL): ''

doctrine:
    dbal:
    # configure these for your database server
        default_connection: zenoshi
        connections:
            zenoshi:
                dbname: heroku_b0a24bf0b4cfa6d
                host: us-cdbr-east-05.cleardb.net
                port: 3306
                user: 'b7b5d1ba311e2b'
                password: '36dc1051'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.0.17'