parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    # env(DATABASE_URL): ''

doctrine:
    dbal:
    # configure these for your database server
        default_connection: zenoshi
        connections:
            zenoshi:
                dbname: heroku_e8d729dc8cfaf03
                host: us-cdbr-east-05.cleardb.net
                port: 3306
                user: 'bedc7a02f52de1'
                password: '049905b1'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.0.17'