parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    # env(DATABASE_URL): ''

doctrine:
    dbal:
    # configure these for your database server
        default_connection: zenoshi
        connections:
            zenoshi:
                dbname: az8lyu5njajf84ao
                host: d9c88q3e09w6fdb2:cbetxkdyhwsb:us-east-1:rds:amazonaws:com:3306
                port: 3306
                user: 'qk5ip2ctpleodp3y'
                password: 'k97z43nh1kqwjvrl'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.0.17'
