parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    # env(DATABASE_URL): ''

doctrine:
    dbal:
    # configure these for your database server
        default_connection: zenoshi
        connections:
            zenoshi:
                dbname: stu7oi68qomsjyjn
                host: phtfaw4p6a970uc0.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
                port: 3306
                user: 'ln74dfk9u7zri76k'
                password: 'm11uau31mxrgdgrw'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.0.17'