nelmio_cors:
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['^https?:\/\/(.*\.)?giffits\.de$']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'appKey']
            expose_headers: ['Link']
            max_age: 3600