parameters:
    checkDuplicated:
        merchant:
            enabled: true
            type: 'AND'
            fields: ['merchantName', 'country']
        product:
            enabled: true
            type: 'AND'
            fields: ['name', 'idMerchant']
        reward:
            enabled: true
            type: 'AND'
            fields: ['nameReward', 'price']
        catalogue:
            enabled: true
            type: 'AND'
            fields: ['type', 'name']
        receip:
            enabled: true
            type: 'AND'
            fields: ['merchantName', 'amount', 'dateEmission']