parameters:
    checkDuplicated:
        merchant:
            enabled: true
            type: 'AND'
            fields: ['merchantName', 'country']
        product:
            enabled: true
            type: 'AND'
            fields: ['name', 'idMerchant']
