# infrastructure/containers/nginx/Dockerfile

FROM nginx:alpine

# Custom nginx configuration for this app
COPY ./infrastructure/containers/nginx/default.conf /etc/nginx/conf.d/default.conf
#COPY ./public /var/www/app