#parameters:
#    # Adds a fallback DATABASE_URL if the env var is not set.
#    # This allows you to run cache:warmup even if your
#    # environment variables are not available yet.
#    # You should not need to change this value.
#     env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%';

    orm:
        default_entity_manager: zenoshi
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            auto_mapping: true
            zenoshi:
                connection: zenoshi
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App