name: Symfony

on:
  push:
    branches: [ master ]

jobs:
  symfony-tests:

    defaults:
      run:
        working-directory: ./app

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
    - name: Clean composer cache
      run: composer clear-cache
    - name: Build process
      working-directory: ./
      run: | 
        rm ./docker-compose.override.yaml
        docker-compose build --no-cache
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push image
      run: |
        IMAGE_PHP_ID=docker.pkg.github.com/${{ secrets.DOCKER_USERNAME }}/zenoshi/php_zenoshi:latest
        IMAGE_APACHE_ID=docker.pkg.github.com/${{ secrets.DOCKER_USERNAME }}/zenoshi/apache_zenoshi:latest
        
        docker tag php:local $IMAGE_PHP_ID
        docker push $IMAGE_PHP_ID
        
        docker tag apache:local $IMAGE_APACHE_ID
        docker push $IMAGE_APACHE_ID
    - name: Deploy stack
      uses: appleboy/ssh-action@master
      env:
        DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      with: 
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        envs: DOCKER_TOKEN,DOCKER_USER   
        script: |
          IMAGE_PHP_ID=docker.pkg.github.com/$DOCKER_USER/zenoshi/php_zenoshi:latest
          IMAGE_APACHE_ID=docker.pkg.github.com/$DOCKER_USER/zenoshi/apache_zenoshi:latest
          echo "$DOCKER_TOKEN" | sudo docker login docker.pkg.github.com -u $DOCKER_USER --password-stdin
          sudo docker pull $IMAGE_PHP_ID
          sudo docker pull $IMAGE_APACHE_ID
          cd ~
          sudo docker stack rm api-zenoshi
          sleep 40
          sudo docker stack deploy -c zenoshi-stack.yml api-zenoshi
